/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "STM32F4xx.h"
#include <stdint.h>
#include "STM32Fxx_GPIO_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{
    /* Loop forever */
	    for(;;);
	    GPIO_handle_t GPIOLED;
	    GPIOLED.pGPIOx = GPIOD;
	    GPIOLED.pin_config.GPIO_PinNumber = GPIO_Pin_Number_15;
	    GPIOLED.pin_config.GPIO_PinMode = GPIO_Mode_out;
	    GPIOLED.pin_config.GPIO_PinSpeed = GPIO_SpeedControl_high;
	    GPIOLED.pin_config.GPIO_PinOType = GPIO_OType_pushpull ;
	    GPIOLED.pin_config.GPIO_PinPuPdControl = GPIO_PuPdControl_up;

}
